markdown: kramdown
safe: false
permalink: /blog/posts/:title
exclude:
  - README.md

host: cuicui.info

blog:
    name: Silver Gao
    desc: 专注于视频
   
custom:
    category:
        works: 作品
        thinking: 闭门思考
        experience: 问题即经验
        discovery: 日新月异
        criticism: 非专业吐槽
        communication: 交流分享
    categories:
      - name:  works
        title: 作品
      
      - name:  thinking
        title: 闭门思考

      - name:  experience
        title: 问题即经验

      - name:  discovery
        title: 日新月异

      - name:  criticism
        title: 非专业吐槽

      - name: communication
        title: 交流分享

    scrollingLoadCount: 2                          # 滚屏自动加载文章数量，“0”为关闭

meta:
    author:
        name: silver
        email: 18826484115@163.com
        disqus: ""                     				# Disqus缩略标识
        gcse: 000346898720731947188:13h55x32l0y     # Google自定义搜索标识ID
        github: none                          		# GitHub账号
        gravatar: /images/portrait.png  			# Gravatar头像标识

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
